### PR TITLE
Standardize frontmatter across Tutorials

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
Related to https://github.com/GenericMappingTools/agu24workshop/issues/1#issuecomment-2518793665, this PR aims to standardize the frontmatter across the tutorials:

- [ ] Mention pre-workshop (Jupyter book, GitHub, AGU Session) 
- [ ] History (author, creation date, recommended versions)
- [ ] Consistent titles, also with intro page (if you don't like to have emojis in your tutorial, just comment on this 🙂)
- [ ] Links to the PyGMT documentation
- [ ] Mention the GitHub repo for errors and the GMT forum for questions
- [ ] Make headings consistent - **Please check for your tutorial if that the structure of headings is correct!**

### CODE REVIEW

**Review by Esteban82 — APPROVED** [review]

**Review by andrebelem — APPROVED** [review]
Perfect ! All good.

**Review by maxrjones — APPROVED** [review]
This is great! I pushed a couple small changes rather than providing a review given the limited time remaining. Thank you for these improvements!

**Comment by maxrjones** [comment]
@yvonnefroehlich are you planning to make any more changes to this? It'd be great to merge if not

**Comment by yvonnefroehlich** [comment]
> This is great! I pushed a couple small changes rather than providing a review given the limited time remaining. Thank you for these improvements!

No worries! This is totally fine. And thanks for doing the rst related stuff 🙂.

> @yvonnefroehlich are you planning to make any more changes to this? It'd be great to merge if not

At the moment I will not work on this. So, feel free to merge this PR. Then people can continue with other PRs (code linting etc.).

**Pull request merged**
